name: spritewidget
description: A sprite toolkit built on top of Flutter
version: 0.9.8
author: Viktor Lidholt <viktorlidholt@gmail.com>
homepage: http://spritewidget.com
environment:
  sdk: ">=1.23.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
