name: spritewidget
description: SpriteWidget is an open source toolkit for building complex, high performance animations and 2D games with Flutter.
version: 0.9.11
author: Viktor Lidholt <viktorlidholt@gmail.com>
homepage: http://spritewidget.com
environment:
  sdk: ">=1.23.0 <3.0.0"
  flutter: ">=0.1.7 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
