name: spritewidget
description: A sprite toolkit built on top of Flutter
version: 0.9.3
author: Viktor Lidholt <viktorlidholt@gmail.com>
homepage: http://spritewidget.com

dependencies:
  flutter:
    sdk: flutter
